replicaCount: 2

image:
  repository: worknest
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  targetPort: 8000

django:
  debug: "False"
  allowedHosts: "*"

postgresql:
  image: postgres:18-alpine
  database: worknest
  username: worknest_user
  password: worknest_password
  port: 5432
  storage: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70