apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worknest.fullname" . }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-this-in-production"
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}